<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>RouterPlus.Infrastructure</RootNamespace>
    <AssemblyName>RouterPlus.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="RouterPlus.Core.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RouterPlus.Core\RouterPlus.Core.csproj" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>
</Project>
