path = r'E:\GitHub\9router-plus\src\RouterPlus.Core\Providers\ProviderDefinition.cs'
with open(path, 'r', encoding='utf-8') as f:
    s = f.read()
old = (
    'public sealed record ProviderDefinition(\n'
    '    ProviderKind Kind,\n'
    '    string DisplayName,\n'
    '    string DashboardPath,\n'
    '    string QuickLink,\n'
    '    WorkflowKind Workflow,\n'
    '    bool RenamesConnection)\n'
    '{\n'
    '    public string BuildDashboardUrl(string dashboardBaseUrl)\n'
    '    {\n'
    '        ArgumentException.ThrowIfNullOrWhiteSpace(dashboardBaseUrl);\n'
    '        return $"{dashboardBaseUrl.TrimEnd(\'/\')}{DashboardPath}";\n'
    '    }\n'
    '}'
)
new = (
    'public sealed record ProviderDefinition(\n'
    '    ProviderKind Kind,\n'
    '    string DisplayName,\n'
    '    string DashboardPath,\n'
    '    string QuickLink,\n'
    '    WorkflowKind Workflow,\n'
    '    bool RenamesConnection)\n'
    '{\n'
    '    public string ShortDisplayName => Kind switch\n'
    '    {\n'
    '        ProviderKind.Codex => "Codex",\n'
    '        ProviderKind.Kiro => "Kiro",\n'
    '        ProviderKind.OpenRouter => "OpenR",\n'
    '        ProviderKind.Ollama => "Ollama",\n'
    '        ProviderKind.Kimchi => "Kimchi",\n'
    '        _ => DisplayName\n'
    '    };\n'
    '\n'
    '    public string Glyph => Kind switch\n'
    '    {\n'
    '        ProviderKind.Codex => "\u2728",\n'
    '        ProviderKind.Kiro => "\U0001F680",\n'
    '        ProviderKind.OpenRouter => "\U0001F9E0",\n'
    '        ProviderKind.Ollama => "\U0001F999",\n'
    '        ProviderKind.Kimchi => "\U0001F33F",\n'
    '        _ => "\u25CF"\n'
    '    };\n'
    '\n'
    '    public string BuildDashboardUrl(string dashboardBaseUrl)\n'
    '    {\n'
    '        ArgumentException.ThrowIfNullOrWhiteSpace(dashboardBaseUrl);\n'
    '        return $"{dashboardBaseUrl.TrimEnd(\'/\')}{DashboardPath}";\n'
    '    }\n'
    '}'
)
assert old in s, 'anchor not found'
s = s.replace(old, new, 1)
with open(path, 'w', encoding='utf-8') as f:
    f.write(s)
print('Done')
