<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>RouterPlus.Updater</RootNamespace>
    <AssemblyName>RouterPlus.Updater</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RouterPlus.Core\RouterPlus.Core.csproj" />
  </ItemGroup>
</Project>
